apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    name: nginx-pod1
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
  - name: nginx-pod1
    image: nginx:1.14
    volumeMounts:
    - name: cephrbd
      mountPath: /usr/share/nginx/html
  volumes:
  - name: cephrbd
    persistentVolumeClaim:
      claimName: rbd-claim

